version: "2.1"
services:
  testo:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["npm", "run", "test:watch"]
    environment:
      NODE_ENV: development
      APP_NAME: testo
      APP_VERSION: '0.0.1'
      REDIS_PREFIX: testo
      JWT_EXPIRES_IN: 1d
      JWT_SECRET: the_cake_is_a_lie
      LOG_PATH: /var/log/testo
      LOG_LEVEL: info
      FILE_NAME: api.combined.log
      MAX_SIZE: 10m
      MAX_FILES: 5
      SPLUNK_INDEX: test
      LOGIN_URL: https://na110.salesforce.com
      CLIENT_ID: 3MVG98hdjyNB1QTl31E_eqyWHfEOMT.xvNufQvnWPnKkJ2BY4.QhL9km0zbJQ_S62_.ifHhFpTxZxmzJJx67b
      CLIENT_SECRET: B2D19AAB10F4936A7C18FDFA10912FC9422E95C6CA7B5D1773C2E076BA2E785F
      APP_URL: https://localhost:8443
      REDIRECT_URI: https://localhost:8443/token
    volumes:
      - ./src:/home/testo/src
      - ./volumes:/home/testo/volumes
      - ./volumes/logs:/var/log/testo
      - ./volumes/certs:/opt/testo/certs
    ports:
      - "8443:8443"

  redis:
    image: redis
